name: Deploy Python Backend
on:
  push:
    paths:
      - 'backend-python/**'
    branches:
      - main
      - master

jobs:
  deploy:
    name: Deploy Python app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --app convergsai-python
        working-directory: backend-python
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
