name: Deploy Node Backend
on:
  push:
    paths:
      - 'backend-node/**'
    branches:
      - main
      - master

jobs:
  deploy:
    name: Deploy Node app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --app convergsai-node
        working-directory: backend-node
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
